[api]
base_path = '/'
key = 'API_SECRET_GOES_BRRRRRRR'
lifespan = 1

[database]
generated = true

[database.development]
host = 'localhost'
mode = 'memory'
pass = 'root'
port = 8000
protocol = 'http'
user = 'root'

[database.production]
host = 'localhost'
mode = 'file://data/database'
pass = 'root'
port = 8000
protocol = 'http'
user = 'root'

[gin]
[gin.development]
mode = 'debug'
trusted_proxies = ['172.0.0.1']

[gin.production]
mode = 'release'
trusted_proxies = ['172.0.0.1']

[storage]
content_root = 'data/images'
