[database.development]
user = "root"
pass = "root"
host = "localhost"
port = 8000
protocol = "http"
mode = "memory"

[database.production]
user = "root"
pass = "root"
host = "localhost"
port = 8000
protocol = "http"
mode = "memory"

[gin.development]
mode = "debug"
trusted_proxies = ["172.0.0.1"]

[gin.production]
mode = "release"
trusted_proxies = ["172.0.0.1"]

[api]
base_path = "/"
lifespan = 1
key = "API_SECRET_GOES_BRRRRRRR"