[api]
base_path = '/'
key = 'API_SECRET_GOES_BRRRRRRR'
lifespan = 1

[database]
executable = './surrealdb'
generated = false

[database.development]
db = 'bus-stats'
host = 'localhost'
mode = 'memory'
ns = 'buonotti'
pass = 'root'
port = 8000
protocol = 'http'
user = 'root'

[database.production]
db = 'bus-stats'
host = 'localhost'
mode = 'file://data/database'
ns = 'buonotti'
pass = 'root'
port = 8000
protocol = 'http'
user = 'root'

[gin]
[gin.development]
allow_origin = '*'
mode = 'debug'
trusted_proxies = ['172.0.0.1']

[gin.production]
allow_origin = '*'
mode = 'release'
trusted_proxies = ['172.0.0.1']

[storage]
content_root = 'data/images'
