version: "3"

tasks:
  docker:
    desc: "Run a docker container with the api"
    deps:
      - build_linux_amd64
    cmds:
      - docker build . -t bus-stats-api
      - docker run --rm -p 8080:8080 bus-stats-api
  dev:
    desc: "Runs the api in development mode"
    cmds:
      - go build && ./bus-stats-api{{if eq OS "windows"}}.exe{{end}} start --dev
  run:
    desc: "Runs the api in production mode"
    cmds:
      - go build && ./bus-stats-api{{if eq OS "windows"}}.exe{{end}} start
  release:
    desc: "Builds release binaries"
    deps:
      - build_linux_amd64
      - build_linux_arm64
      - build_darwin_amd64
      - build_darwin_arm64
      - build_windows_amd64

  build_linux_amd64:
    internal: true
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o release/bus-stats-linux-amd64

  build_linux_arm64:
    internal: true
    env:
      GOOS: linux
      GOARCH: arm64
    cmds:
      - go build -o release/bus-stats-linux-arm64

  build_darwin_amd64:
    internal: true
    env:
      GOOS: darwin
      GOARCH: amd64
    cmds:
      - go build -o release/bus-stats-darwin-amd64

  build_darwin_arm64:
    internal: true
    env:
      GOOS: darwin
      GOARCH: arm64
    cmds:
      - go build -o release/bus-stats-darwin-arm64
  
  build_windows_amd64:
    internal: true
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -o release/bus-stats-windows-amd64.exe